customers = [
    {
        "id": 1,
        "name": "TechNova Solutions",
        "city": "Austin",
        "state": "Texas",
        "country": "United States",
    },
    {
        "id": 2,
        "name": "GreenEdge Innovations",
        "city": "San Francisco",
        "state": "California",
        "country": "United States",
    },
    {
        "id": 3,
        "name": "Skyline Dynamics",
        "city": "Denver",
        "state": "Colorado",
        "country": "United States",
    },
    {
        "id": 4,
        "name": "Oceanic Synergy Corp",
        "city": "Miami",
        "state": "Florida",
        "country": "United States",
    },
    {
        "id": 5,
        "name": "Quantum Apex Systems",
        "city": "Seattle",
        "state": "Washington",
        "country": "United States",
    },
    {
        "id": 6,
        "name": "Summit Ventures Inc",
        "city": "Boulder",
        "state": "Colorado",
        "country": "United States",
    },
    {
        "id": 7,
        "name": "FusionCore Analytics",
        "city": "Chicago",
        "state": "Illinois",
        "country": "United States",
    },
    {
        "id": 8,
        "name": "Pinnacle Horizon Ltd",
        "city": "New York",
        "state": "New York",
        "country": "United States",
    },
    {
        "id": 9,
        "name": "TerraSphere Enterprises",
        "city": "Portland",
        "state": "Oregon",
        "country": "United States",
    },
    {
        "id": 10,
        "name": "NeoStream Global",
        "city": "Los Angeles",
        "state": "California",
        "country": "United States",
    },
    {
        "id": 11,
        "name": "BrightPath Technologies",
        "city": "Phoenix",
        "state": "Arizona",
        "country": "United States",
    },
    {
        "id": 12,
        "name": "EchoWave Systems",
        "city": "Boston",
        "state": "Massachusetts",
        "country": "United States",
    },
    {
        "id": 13,
        "name": "VentureCore Industries",
        "city": "Dallas",
        "state": "Texas",
        "country": "United States",
    },
    {
        "id": 14,
        "name": "EcoSphere Networks",
        "city": "San Diego",
        "state": "California",
        "country": "United States",
    },
    {
        "id": 15,
        "name": "Ascendix Global",
        "city": "Charlotte",
        "state": "North Carolina",
        "country": "United States",
    },
    {
        "id": 16,
        "name": "NovaFusion Technologies",
        "city": "Atlanta",
        "state": "Georgia",
        "country": "United States",
    },
    {
        "id": 17,
        "name": "CloudCrest Solutions",
        "city": "Salt Lake City",
        "state": "Utah",
        "country": "United States",
    },
    {
        "id": 18,
        "name": "PrimeLogic Systems",
        "city": "Columbus",
        "state": "Ohio",
        "country": "United States",
    },
    {
        "id": 19,
        "name": "UrbanAxis Group",
        "city": "Nashville",
        "state": "Tennessee",
        "country": "United States",
    },
    {
        "id": 20,
        "name": "Hyperion Edge",
        "city": "Raleigh",
        "state": "North Carolina",
        "country": "United States",
    },
]
