opportunities = [
    {
        "id": 1,
        "name": "Cloud Migration Project",
        "customer_id": 1,
        "amount": 150000,
        "stage": "Open",
    },
    {
        "id": 2,
        "name": "AI Integration Suite",
        "customer_id": 2,
        "amount": 200000,
        "stage": "Closed Won",
    },
    {
        "id": 3,
        "name": "ERP Implementation",
        "customer_id": 3,
        "amount": 180000,
        "stage": "Closed Lost",
    },
    {"id": 4, "name": "Cybersecurity Upgrade", "customer_id": 4, "amount": 125000, "stage": "Open"},
    {"id": 5, "name": "CRM Expansion", "customer_id": 5, "amount": 95000, "stage": "Closed Won"},
    {
        "id": 6,
        "name": "Data Warehousing Solution",
        "customer_id": 6,
        "amount": 220000,
        "stage": "Open",
    },
    {
        "id": 7,
        "name": "Cloud Cost Optimization",
        "customer_id": 7,
        "amount": 85000,
        "stage": "Closed Lost",
    },
    {
        "id": 8,
        "name": "Custom Software Development",
        "customer_id": 8,
        "amount": 175000,
        "stage": "Open",
    },
    {
        "id": 9,
        "name": "Network Security Audit",
        "customer_id": 9,
        "amount": 110000,
        "stage": "Closed Won",
    },
    {
        "id": 10,
        "name": "IT Infrastructure Revamp",
        "customer_id": 10,
        "amount": 300000,
        "stage": "Open",
    },
    {
        "id": 11,
        "name": "Business Intelligence Suite",
        "customer_id": 11,
        "amount": 195000,
        "stage": "Closed Won",
    },
    {
        "id": 12,
        "name": "HR Tech Modernization",
        "customer_id": 12,
        "amount": 160000,
        "stage": "Closed Lost",
    },
    {
        "id": 13,
        "name": "Supply Chain Automation",
        "customer_id": 13,
        "amount": 210000,
        "stage": "Open",
    },
    {
        "id": 14,
        "name": "5G Network Expansion",
        "customer_id": 14,
        "amount": 275000,
        "stage": "Closed Won",
    },
    {
        "id": 15,
        "name": "IoT Implementation",
        "customer_id": 15,
        "amount": 120000,
        "stage": "Closed Lost",
    },
    {
        "id": 16,
        "name": "Machine Learning Framework",
        "customer_id": 16,
        "amount": 230000,
        "stage": "Open",
    },
    {
        "id": 17,
        "name": "Hybrid Cloud Deployment",
        "customer_id": 17,
        "amount": 250000,
        "stage": "Closed Won",
    },
    {
        "id": 18,
        "name": "Enterprise Mobility Solutions",
        "customer_id": 18,
        "amount": 140000,
        "stage": "Open",
    },
    {
        "id": 19,
        "name": "Edge Computing Strategy",
        "customer_id": 19,
        "amount": 180000,
        "stage": "Closed Lost",
    },
    {
        "id": 20,
        "name": "Blockchain for Logistics",
        "customer_id": 20,
        "amount": 265000,
        "stage": "Open",
    },
]
